version: '3.8'

services:
  ark:
    image: hermsi/ark-server:tools-1.6.61a
    restart: always
    volumes:
      - ./ark-server:/app
      - ./ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_MAP=${SERVER_MAP}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - UPDATE_ON_START=${UPDATE_ON_START}
      - BACKUP_ON_STOP=${BACKUP_ON_STOP}
      - PRE_UPDATE_BACKUP=${PRE_UPDATE_BACKUP}
      - WARN_ON_STOP=${WARN_ON_STOP}
    ports:
      # Port for connections from ARK game client
      - "0.0.0.0:7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "0.0.0.0:7778:7778/udp"
      # RCON management port
      - "0.0.0.0:27020:27020/tcp"
      # Steam's server-list port
      - "0.0.0.0:27015:27015/udp"

